In [1]:

from pathlib import Path
import numpy as np
import pandas as pd
import os
from utils import *
from pine_functions import *

In [2]:
ticker = "AAPL"
file = ticker+".csv"
data_path = Path(os.getcwd()).parent # perhaps set to external harddrive to accomodate large amount of data
path = data_path / 'stock price data'/"company stock price daily"/file
stock = pd.read_csv(path)
stock['date'] = pd.to_datetime(stock['date'])
stock = stock.sort_values(by='date').reset_index(drop=True) 
stock

,date,open,high,low,close,adjClose,volume,unadjustedVolume,change,changePercent,vwap,label,changeOverTime,Symbol
0,2010-01-04,7.6225,7.6607,7.5850,7.6432,6.496293,493719800,17632850,0.0207,0.27156,7.63,"January 04, 10",0.002716,AAPL
1,2010-01-05,7.6643,7.6996,7.6161,7.6564,6.507526,601901216,21496472,-0.0079,-0.10308,7.67,"January 05, 10",-0.001031,AAPL
2,2010-01-06,7.6564,7.6868,7.5268,7.5346,6.404015,552158376,19719942,-0.1218,-1.59000,7.61,"January 06, 10",-0.015900,AAPL
3,2010-01-07,7.5625,7.5714,7.4661,7.5207,6.392176,477129296,17040332,-0.0418,-0.55273,7.51,"January 07, 10",-0.005527,AAPL
4,2010-01-08,7.5107,7.5714,7.4664,7.5707,6.434673,447872124,15995433,0.0600,0.79886,7.53,"January 08, 10",0.007989,AAPL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3397,2023-07-05,191.5650,192.9800,190.6200,191.3300,191.330002,46896861,46920300,-0.2350,-0.12267,191.58,"July 05, 23",-0.001227,AAPL
3398,2023-07-06,189.8400,192.0200,189.2000,191.8100,191.809998,45155523,45094300,1.9700,1.04000,190.82,"July 06, 23",0.010400,AAPL
3399,2023-07-07,191.4100,192.6700,190.2400,190.6800,190.679993,46757498,46778000,-0.7300,-0.38138,191.42,"July 07, 23",-0.003814,AAPL
3400,2023-07-10,189.2600,189.9900,187.0350,188.6100,188.610001,59912163,59922200,-0.6500,-0.34344,188.36,"July 10, 23",-0.003434,AAPL
3401,2023-07-11,189.1600,189.3000,186.6000,188.0800,188.080002,46522493,46509718,-1.0800,-0.57095,187.82,"July 11, 23",-0.005710,AAPL

In [3]:
sma_length = 200
stock["sma"] = pine_sma(stock["close"], sma_length)
rsi_period = 10
stock["rsi"] = pine_rsi(stock["close"], rsi_period)

In [4]:
stock = stock.dropna().reset_index(drop=True)
stock

,date,open,high,low,close,adjClose,volume,unadjustedVolume,change,changePercent,vwap,label,changeOverTime,Symbol,sma,rsi
0,2010-10-18,11.3739,11.3929,11.2246,11.3571,9.652918,1103638564,39415663,-0.0168,-0.14771,11.23,"October 18, 10",-0.001477,AAPL,8.767174,87.343110
1,2010-10-19,10.8357,11.2061,10.7150,11.0532,9.394601,1232280532,44010019,0.2175,2.01000,11.02,"October 19, 10",0.020100,AAPL,8.784224,69.349615
2,2010-10-20,11.0357,11.2232,10.9596,11.0904,9.426168,721624120,25772290,0.0547,0.49566,11.11,"October 20, 10",0.004957,AAPL,8.801394,70.185009
3,2010-10-21,11.1557,11.2407,10.9571,11.0543,9.395511,551457284,19694903,-0.1014,-0.90895,11.10,"October 21, 10",-0.009090,AAPL,8.818993,68.181266
4,2010-10-22,11.0382,11.0729,10.9393,10.9811,9.333282,372775424,13313408,-0.0571,-0.51729,11.01,"October 22, 10",-0.005173,AAPL,8.836295,64.060753
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3198,2023-07-05,191.5650,192.9800,190.6200,191.3300,191.330002,46896861,46920300,-0.2350,-0.12267,191.58,"July 05, 23",-0.001227,AAPL,154.954475,67.768131
3199,2023-07-06,189.8400,192.0200,189.2000,191.8100,191.809998,45155523,45094300,1.9700,1.04000,190.82,"July 06, 23",0.010400,AAPL,155.160025,68.833301
3200,2023-07-07,191.4100,192.6700,190.2400,190.6800,190.679993,46757498,46778000,-0.7300,-0.38138,191.42,"July 07, 23",-0.003814,AAPL,155.341025,63.356587
3201,2023-07-10,189.2600,189.9900,187.0350,188.6100,188.610001,59912163,59922200,-0.6500,-0.34344,188.36,"July 10, 23",-0.003434,AAPL,155.499575,54.526263
3202,2023-07-11,189.1600,189.3000,186.6000,188.0800,188.080002,46522493,46509718,-1.0800,-0.57095,187.82,"July 11, 23",-0.005710,AAPL,155.671375,52.446728

In [5]:

# stop_loss_price = False
# stop_loss=False
# stop_gain=False
# buy_price = False
long_range = 30
oversell=30
overbuy=70
midline_buy = 40
midline_sell = 60
day_max = 11

day_count = 0
long_in = 0
short_in = 0
long_out = 0
short_out = 0
stock.loc[:, "order"] = 0
for i in range(1,len(stock)):
    stock.loc[i,"long_trend"] = (stock.loc[i,"sma"] > stock.loc[i-1,"sma"])
    stock.loc[i,"short_trend"] = (stock.loc[i,"sma"] < stock.loc[i-1,"sma"])
    if i <= long_range:
        stock.loc[i, "order"] = 0
    else:
        if long_in == 1:
            stock.loc[i, "order"] = 1
            day_count+=1
            long_in = 0
            if stock.loc[i, "rsi"] >= midline_buy:
                long_out = 1
        elif short_in ==1:
            stock.loc[i, "order"] = -1
            day_count+=1
            short_in = 0
            if stock.loc[i, "rsi"] <= midline_sell:
                short_out = 1
        elif long_out == 1:
            stock.loc[i, "order"] = 0
            day_count = 0
            long_out = 0
        elif short_out == 1:
            stock.loc[i, "order"] = 0
            day_count = 0
            short_out = 0
        elif stock.loc[i-1, "order"] == 1:
            if stock.loc[i, "rsi"] >= midline_buy or day_count >= day_max:
                long_out = 1
            stock.loc[i, "order"] = stock.loc[i-1, "order"]
            day_count+=1
        elif stock.loc[i-1, "order"] == -1:
            if stock.loc[i, "rsi"] <= midline_sell or day_count >= day_max:
                short_out = 1
            stock.loc[i, "order"] = stock.loc[i-1, "order"]
            day_count+=1
        # elif stock.loc[i, "close"] >= stock.loc[i,"sma"]:
        elif sum(stock.loc[i-long_range:i, "close"] >= stock.loc[i,"sma"])/long_range >= 0.5 and sum(stock.loc[i-long_range:i,"long_trend"]) >= long_range:
            if stock.loc[i, "rsi"] <= oversell:
                long_in = 1
            stock.loc[i,"order"] = 0
        # elif stock.loc[i, "close"] <= stock.loc[i,"sma"]:
        elif sum(stock.loc[i-long_range:i, "close"] <= stock.loc[i,"sma"])/long_range >= 0.5 and sum(stock.loc[i-long_range:i,"short_trend"]) >= long_range:
            if stock.loc[i, "rsi"] >= overbuy:
                short_in = 1
            stock.loc[i, "order"] = 0
        else:
            stock.loc[i,"order"] = 0
            day_count=0

In [6]:
stock["order"].value_counts()

order
 0    3009
 1     103
-1      91
Name: count, dtype: int64

In [7]:
eval(stock, ticker, {}, opt=True)

(0.10975042629049764, 0.4944256722300898, 0.6216216216216216)

In [8]:

# perhaps set to external harddrive to accomodate large amount of data
data_path = Path(os.getcwd()).parent
buy_orders = []
sell_orders = []
current_order = None
money = 100000
short = None
long = None

for index, row in stock.iterrows():
    if row['order'] > 0:
        if current_order is None and short is None:
            current_order = {"Initial Money": money, 'Buy Date': row['date'], 'Buy Price': stock.loc[index, 'open'], "Shares Purchased": money/stock.loc[index, 'open'], "long/short": "long"}
            long = True
        elif current_order is not None and short is not None:
            current_order['Sell Date'] = row['date']
            current_order['Sell Price'] = row['open']
            current_order["Price Change"] = current_order["Sell Price"] - \
                current_order["Buy Price"]
            current_order["Profit"] = current_order["Price Change"] * \
                current_order["Shares Purchased"] * -1
            current_order["Money After Order"] = current_order["Shares Purchased"] * \
                current_order['Buy Price'] + current_order["Profit"]
            money = current_order["Money After Order"]
            sell_orders.append(current_order)
            short = None
            current_order = {"Initial Money": money, 'Buy Date': row['date'], 'Buy Price': row[
                'open'], "Shares Purchased": money/row['open'], "long/short": "long"}
            long = True
        else:
            continue
    elif row['order'] < 0:
        if current_order is None and long is None:
            current_order = {"Initial Money": money, 'Buy Date': row['date'], 'Buy Price': stock.loc[index, 'open'], "Shares Purchased": money/stock.loc[index, 'open'], "long/short": "short"}
            short = True
        elif current_order is not None and long is not None:
            current_order['Sell Date'] = row['date']
            current_order['Sell Price'] = row['open']
            current_order["Price Change"] = current_order["Sell Price"] - \
                current_order["Buy Price"]
            current_order["Profit"] = current_order["Price Change"] * \
                current_order["Shares Purchased"]
            current_order["Money After Order"] = current_order["Shares Purchased"] * \
                current_order['Buy Price'] + current_order["Profit"]
            money = current_order["Money After Order"]
            sell_orders.append(current_order)
            long = None
            current_order = {"Initial Money": money, 'Buy Date': row['date'], 'Buy Price': row[
                'open'], "Shares Purchased": money/row['open'], "long/short": "short"}
            short = True
        else:
            continue
    elif row['order'] == 0:
        if current_order is not None:
            current_order['Sell Date'] = row['date']
            current_order['Sell Price'] = row['open']
            current_order["Price Change"] = current_order["Sell Price"] - \
                current_order["Buy Price"]
            if current_order['long/short'] == "short":
                current_order["Profit"] = current_order["Price Change"] * \
                    current_order["Shares Purchased"] * -1
            elif current_order['long/short'] == "long":
                current_order["Profit"] = current_order["Price Change"] * \
                    current_order["Shares Purchased"]
            current_order["Money After Order"] = current_order["Shares Purchased"] * \
                current_order['Buy Price'] + current_order["Profit"]
            money = current_order["Money After Order"]
            sell_orders.append(current_order)
            current_order = None
            long = None
            short = None

# Create a new DataFrame for buy and sell orders
orders_df = pd.DataFrame(buy_orders + sell_orders)

# maximum drawdown
peak_value = None
maximum_drawdown = 0.0

for index, row in stock.iterrows():
    if row['order'] == 1:
        if peak_value is None:
            peak_value = row['open']
        elif row['open'] > peak_value:
            peak_value = row['open']
        else:
            drawdown = (peak_value - row['open']) / peak_value
            if drawdown > maximum_drawdown:
                maximum_drawdown = drawdown
    if row['order'] == -1:
        if peak_value is None:
            peak_value = row['open']
        elif row['open'] < peak_value:
            peak_value = row['open']
        else:
            drawdown = (row['open'] - peak_value) / peak_value
            if drawdown > maximum_drawdown:
                maximum_drawdown = drawdown
    elif row['order'] == 0:
        # If 'order_column' is 0, reset peak and trough values
        peak_value = None

# ROI
ROI = (orders_df.loc[len(orders_df)-1, "Money After Order"] -
    orders_df.loc[0, "Initial Money"])/orders_df.loc[0, "Initial Money"]
# print(f"ROI: {ROI * 100:.2f}%")
ROI_noStrategy = (stock.loc[len(stock)-1, "close"] -
                stock.loc[0, "close"]) / stock.loc[0, "close"]
# print(f"ROI with no strategy: {ROI_noStrategy * 100:.2f}%")

# Win-Loss Ratio
win_loss_ratio = (orders_df['Profit'] > 0).sum()/len(orders_df) * 100
# print(f"Win-Loss Ratio: {win_loss_ratio:.2f}%")
# Reset the index of the new DataFrame
orders_df.reset_index(drop=True, inplace=True)
# Total Trades
print("Total Trades: {}".format(len(orders_df)))

# Average Win
winning = orders_df[orders_df["Profit"] > 0]
print(
    f"Average Win: {abs(winning['Price Change']/winning['Buy Price']).mean() * 100:.2f}%")

# Average Lose
losing = orders_df[orders_df["Profit"] <= 0]
print(
    f"Average Lose: {abs(losing['Price Change']/losing['Buy Price']).mean() * 100:.2f}%")

# Maximum Drawdown is now stored in 'maximum_drawdown'
print(f"Maximum Drawdown: {maximum_drawdown * 100:.2f}%")

# ROI
print(f"ROI: {ROI * 100:.2f}%")
print(f"ROI with no strategy: {ROI_noStrategy * 100:.2f}%")

# Compounding Annual Return
years = (stock["date"].max()-stock["date"].min()).days/365
print(
    f"Compounding Annual Return: {((orders_df.loc[len(orders_df)-1, 'Money After Order']/orders_df.loc[0, 'Initial Money']) ** (1/years) - 1) * 100:.2f}%")

# Win-Loss Ratio
print(f"Win-Loss Ratio: {win_loss_ratio:.2f}%")
# Profit-Loss Ratio
print(
    f"Profit-Loss Ratio: {winning['Profit'].sum()/-losing['Profit'].sum()}")

# Annual Variance
stock['daily_returns'] = stock['order'] * \
    (stock['close'] / stock['close'].shift(1) - 1)
variance_daily = np.var(stock['daily_returns'].dropna())
# Specify the number of trading days in a year (e.g., 252 for U.S. markets)
trading_days_per_year = 252
# Annualize the variance by multiplying by the number of trading days in a year
variance_annualized = variance_daily * trading_days_per_year
print("Annual Variance: {}".format(variance_annualized))

# Annual Standard Deviation
print("Annual Standard Deviation: {}".format(
    np.sqrt(variance_annualized)))

# Sharoe Ratio
# Calculate the average daily return
average_daily_return = stock['daily_returns'].mean()
# Calculate the daily risk-free rate
annual_rate = 0.04
daily_risk_free_rate = (
    1 + annual_rate) ** (1/trading_days_per_year) - 1
# Calculate the daily excess return
stock['daily_excess_return'] = stock['daily_returns'] - \
    daily_risk_free_rate
# Calculate the standard deviation of daily excess returns as the measure of risk
std_dev_daily_excess_returns = stock['daily_excess_return'].std()
# Calculate the annualized Sharpe Ratio
sharpe_ratio = (average_daily_return /
                std_dev_daily_excess_returns) * np.sqrt(trading_days_per_year)
print(f"Sharpe Ratio: {sharpe_ratio:.4f}")

Total Trades: 37
Average Win: 3.47%
Average Lose: 2.79%
Maximum Drawdown: 11.55%
ROI: 98.22%
ROI with no strategy: 1556.06%
Compounding Annual Return: 5.52%
Win-Loss Ratio: 75.68%
Profit-Loss Ratio: 3.374370306052952
Annual Variance: 0.006926346922085195
Annual Standard Deviation: 0.0832246773624578
Sharpe Ratio: 0.4577

In [9]:
orders_df

,Initial Money,Buy Date,Buy Price,Shares Purchased,long/short,Sell Date,Sell Price,Price Change,Profit,Money After Order
0,100000.000000,2011-06-21,11.3100,8841.732980,long,2011-06-22,11.6129,0.3029,2678.160920,102678.160920
1,102678.160920,2012-05-17,19.4754,5272.197794,long,2012-05-22,20.3411,0.8657,4564.141630,107242.302550
2,107242.302550,2012-10-12,22.4843,4769.652715,long,2012-10-17,23.1739,0.6896,3289.152513,110531.455062
3,110531.455062,2012-10-22,21.8721,5053.536472,long,2012-10-23,22.5357,0.6636,3353.526803,113884.981865
4,113884.981865,2012-11-05,20.8398,5464.782861,long,2012-11-20,20.4254,-0.4144,-2264.606018,111620.375848
5,111620.375848,2013-05-07,16.6061,6721.649023,short,2013-05-15,15.6843,-0.9218,6196.016070,117816.391917
6,117816.391917,2013-07-31,16.2496,7250.417974,short,2013-08-12,16.3164,0.0668,-484.327921,117332.063997
7,117332.063997,2013-08-14,17.7814,6598.584138,short,2013-08-28,17.3571,-0.4243,2799.779250,120131.843246
8,120131.843246,2014-01-29,17.9982,6674.658757,long,2014-02-10,18.5236,0.5254,3506.865711,123638.708958
9,123638.708958,2014-12-17,26.7800,4616.830058,long,2014-12-18,27.9675,1.1875,5482.485694,129121.194652
10,129121.194652,2015-07-09,30.9625,4170.244478,long,2015-07-13,31.2575,0.2950,1230.222121,130351.416773
11,130351.416773,2015-08-04,29.3550,4440.518371,long,2015-08-11,29.4525,0.0975,432.950541,130784.367314
12,130784.367314,2015-08-24,23.7175,5514.256027,long,2015-08-27,28.0575,4.3400,23931.871156,154716.238470
13,154716.238470,2016-03-07,25.5975,6044.193318,short,2016-03-23,26.6200,1.0225,-6180.187668,148536.050802
14,148536.050802,2016-03-30,27.1625,5468.423407,short,2016-04-08,27.2275,0.0650,-355.447521,148180.603280
15,148180.603280,2016-04-14,27.9050,5310.181089,short,2016-04-18,27.2225,-0.6825,3624.198593,151804.801873
16,151804.801873,2016-07-19,24.8900,6099.027797,short,2016-07-25,24.5625,-0.3275,1997.431604,153802.233477
17,153802.233477,2016-07-28,25.7075,5982.776757,short,2016-08-15,27.0350,1.3275,-7942.136145,145860.097332
18,145860.097332,2016-08-17,27.2750,5347.757922,short,2016-08-25,26.8475,-0.4275,2286.166512,148146.263844
19,148146.263844,2016-11-11,26.7800,5531.974005,long,2016-11-17,27.4525,0.6725,3720.252518,151866.516362
20,151866.516362,2017-06-13,36.7900,4127.929230,long,2017-06-20,36.7175,-0.0725,-299.274869,151567.241493
21,151567.241493,2017-09-22,38.0050,3988.086870,long,2017-09-28,38.4725,0.4675,1864.430612,153431.672105
22,153431.672105,2018-01-30,41.3813,3707.753795,long,2018-02-13,40.4875,-0.8938,-3313.990342,150117.681763
23,150117.681763,2018-03-26,42.0175,3572.741876,long,2018-03-27,43.4200,1.4025,5010.770481,155128.452244
24,155128.452244,2018-06-26,45.7475,3390.971140,long,2018-06-29,46.5725,0.8250,2797.551191,157926.003434
25,157926.003434,2018-11-14,48.4750,3257.885579,long,2018-12-03,46.1150,-2.3600,-7688.609966,150237.393468
26,150237.393468,2019-02-05,43.2150,3476.510320,short,2019-02-22,42.8950,-0.3200,1112.483302,151349.876771
27,151349.876771,2020-02-26,71.6325,2112.866042,long,2020-03-03,75.9175,4.2850,9053.630991,160403.507762
28,160403.507762,2021-02-23,123.7600,1296.085228,long,2021-03-02,128.4100,4.6500,6026.796308,166430.304070
29,166430.304070,2021-03-09,119.0300,1398.221491,long,2021-03-10,121.6900,2.6600,3719.269166,170149.573236
30,170149.573236,2021-05-13,124.5800,1365.785626,long,2021-05-17,126.8200,2.2400,3059.359801,173208.933037
31,173208.933037,2021-09-21,143.9300,1203.424811,long,2021-09-23,146.6500,2.7200,3273.315486,176482.248523
32,176482.248523,2022-01-24,160.0200,1102.876194,long,2022-01-31,170.1600,10.1400,11183.164605,187665.413127
33,187665.413127,2022-03-15,150.9000,1243.640909,long,2022-03-17,158.6100,7.7100,9588.471406,197253.884534
34,197253.884534,2022-04-27,155.9100,1265.177888,long,2022-04-29,161.8400,5.9300,7502.504876,204756.389410
35,204756.389410,2022-09-07,154.8250,1322.502111,long,2022-09-12,159.5900,4.7650,6301.722561,211058.111971
36,211058.111971,2023-01-25,140.8900,1498.034722,short,2023-02-10,149.4600,8.5700,-12838.157567,198219.954404

In [10]:
from algo_4 import *
from utils import *
# algo4("AAL")
ticker = "WMT"
eval_open(algo4(ticker), ticker, variables={}, opt=True)

(0.06792694649150913, 0.2626507307118703, 0.7096774193548387)